### ISSUE TITLE
[META] Desirable Features List

### ISSUE THREAD

**Issue by bacongobbler** [brigadecore/brigade#11]
<a href="https://github.com/technosophos"><img src="https://avatars1.githubusercontent.com/u/89193?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [technosophos](https://github.com/technosophos)**
_2017-08-15 14:20:04_

----

This ticket captures "desirable features" to add to Acid.

## User Interface

- [x] **API server: As a front-end author, I want a JSON/REST API server to tell me about builds**
  - Started an API in https://github.com/deis/acid/pull/119
- [x] **Log page: As a user, I want to see the logs for a build**
- [x] Landing page: As a user, I want to see my main landing page
- [ ] Project page: As a user, I want a form for creating a new project
... (Ask @flynnduism for the rest of these)
- [x] CLI: As a user, I want a simple CLI for dumping the logs of a particular build, and/or checking the status of a build (This should consume the REST API)

## Gateways:

- [x] VSTS: As a VSTS user, I want webhook support for push requests
https://www.visualstudio.com/en-us/docs/integrate/api/hooks/subscriptions
- [x] GitLab: As a GL user, I want webhook support https://docs.gitlab.com/ee/api/projects.html#hooks
- [x] Bitbucket: As a BB user, I want webhook support https://developer.atlassian.com/bitbucket/guides/getting-started.html
- [ ] GitHub: As GitHub user, I want support of "pull request comment" hooks to approve whether a build runs
- [x] Slack: As a Slack user, I want chat-ops-like bot-to-Acid hooks
- [ ] Cron: As a user, I want to schedule tasks to run periodically

## Core

- [x] **chart: As a user, I want to install GitHub hooks + Controller + Worker from Helm (mostly done)**
- [x] project chart: As a user, I want to install a project from Helm (mostly done)
- [x] **e2e/acceptance tests: As an admin, I want to run a set of acceptance tests to validate the entire system**

## Examples and Docs:

- [x] Acid-builds-Acid: As a user, I want to be able to use Acid's `acid.js` as an example
- [x] Other projects: As a user, I want to see other examples of Acid builds
- [x]  `acid.js` docs: As a user, I want a guide for writing Acid.js, including API and best practices
- [x] **Setup docs: As a user, I want a quick install and a detailed guide**
- [x] Kubernetes integration: As a user, I want to know how to create Kubernetes-centered builds
- [x] Docker builds: As a user, I want to know how to build Docker images
- [x] Azure Blob Storage (s3, gcs, minio...): As a user, I want examples of storing artifacts in object storage
- [x] ACR (Quay, etc): As a user, I want examples of using a private Docker registry for my images
- [x] Passing data between Jobs: As a user, I want examples of passing data through the job pipeline
- [x] Parallel builds: As a user, I want examples of parallel and serial builds
- [ ] Docker Builds: As a user, I want to know how to build Docker images safely

## Worker

- [ ]  Debugging: As a user, I want a way to debug a session via a debugger-like interface
- [x] Cache: As a user, I want to write a Job that shares a cache of data across instances (example: cache `vendor/` tree from build to build) **WIP HERE: #117 **
- [x] Shared Volume: As a user, I want to write Jobs that share a common file storage system so I can share data via (something like) File IO

## Super Awesome Bonus Features

- [ ] GitHub Hook Installer: As a new user, I want to click a button and have GitHub hooks configured for me.

## Integrations

- [ ] As a Draft user, I want a streamlined Acid experience

## Pre-Launch

- [x]  **Name the product: As a developer who is sick of people telling him that "acid isn't a real name" I want a different name for the product.**

**Comment by bacongobbler** [comment]
**Comment by [technosophos](https://github.com/technosophos)**
_2017-08-15 23:16:06_

----

For the Cron feature, it might be easiest to just use a Kubernetes Cron object pointing to an `lsd`-based launch: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by bacongobbler** [comment]
**Comment by [bacongobbler](https://github.com/bacongobbler)**
_2017-08-23 17:46:07_

----

with #118 we can close out a few topics on the "examples and docs" side of things.

**Comment by bacongobbler** [comment]
**Comment by [bacongobbler](https://github.com/bacongobbler)**
_2017-08-24 15:31:42_

----

For the e2e/acceptance test suites, are we looking for a `helm test` integration with acid, or would the go-ified functional tests in #116 suffice for that ticket item?

**Comment by bacongobbler** [comment]
**Comment by [technosophos](https://github.com/technosophos)**
_2017-08-30 15:47:43_

----

I think the new functional tests are what we had in mind initially.

**Comment by technosophos** [comment]
Most of this is superseded by the splitting of Brigade into its own project. However, I am leaving this open because there are still some valuable notes on it.

**Comment by wstrange** [comment]
A "brig init" feature (like helm init) to initialize all the server side components would be nice.

**Comment by bacongobbler** [comment]
We’ve been experimenting that with `draft init` and found that we ended up re-implementing `helm install/upgrade`. I’d personally say that unless there’s something else we’re doing on the backend it’s probably better to point users at `helm install` instead.

**Comment by mbarison** [comment]
Hi, I am planning to use Brigade as an AI training jobs scheduler, so not in the context of CI/CD.
I would like to have documentation on how to write a Brigade Gateway with custom events.
Thanks!

**Comment by bacongobbler** [comment]
I've seen you have found the documentation which was posted in #231. :)

**Comment by lukepatrick** [comment]
## Gateways:
- [x] GitLab
- [x] Bitbucket

## Examples and Docs:
- [x] Blob Storage

**Comment by krancour** [comment]
Closing due to staleness. Please reopen if appropriate.
