### ISSUE TITLE
Meta: v2 Topic Docs

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#1508]
Meta issue to track creation/updates to docs under the [topics section](https://github.com/brigadecore/brigade/tree/v2/docs/content/topics).

This will help track work if/when multiple contributors pitch in.

Currently setting with the beta.2 milestone, but full completion might carry over into later beta releases.

Here's what the Topics index currently looks like (the links only work in the context of the docs site):

## Table of Contents

- [ ] Architecture
  - [ ] [Brigade Design](design): A high-level explanation of how Brigade is designed.
  - [ ] [Brigade Roles](roles): The main roles of interaction within Brigade
- [ ] Operators 
  - [ ] [Overview](operators/index): An overview of the Operator role in Brigade
  - [ ] [Deployment](operators/deploy): How to deploy and manage Brigade
  - [ ] [Securing Brigade](operators/security): Securing Brigade via TLS, Ingress and Third-Party Auth
  - [ ] [Storage](operators/storage): Storage options and configuration for Brigade
  - [ ] [Gateways](operators/gateways): Using and developing Brigade gateways
- [ ] Administrators
  - [ ] [Overview](administrators/index): An overview of the Administrator role in Brigade
  - [ ] [Authentication](administrators/authentication): Authentication strategies in Brigade
  - [ ] [Authorization](administrators/authorization): Authorization setup in Brigade
- [ ] Project Developers
  - [ ] [Overview](project-developers/index): An overview of the Project Developer role in Brigade
  - [ ] [Projects](project-developers/projects): Creating and managing Brigade Projects
  - [ ] [Events](project-developers/events): Understanding and handling Brigade Events
  - [ ] [Using Secrets](project-developers/secrets): Using secrets in Brigade Projects
  - [ ] [Using the Brigade CLI](project-developers/brig): Using the brig CLI to interact with Brigade
  - [ ] [Brigterm](project-developers/brigterm): Using the Brigterm visualization utility
- [ ] Scripting
  - [ ] [Overview](scripting/index): Scripting in Brigade
  - [ ] [Scripting Guide](scripting/guide): A guide to writing `brigade.js`/`brigade.ts` scripts in Brigade
  - [ ] [Brigadier](scripting/brigadier): Brigadier: the JS/TS library for Brigade scripts
  - [ ] [Scripting Guide - Advanced](scripting/advanced): Advanced examples for Brigade scripts.
  - [ ] [Adding dependencies](scripting/dependencies): How to add local dependencies and NPM packages to your Brigade scripts.
  - [ ] [Workers](scripting/workers): More information regarding the Brigade Worker.
- [ ] Contributing to Brigade Development
  - [ ] [Brigade Developers Guide](developers): A guide for people who want to modify Brigade's code.
- [ ] Examples
  - [ ] [Example Projects](examples): Example Brigade projects

**Comment by krancour** [comment]
@vdice this will be super helpful for tracking doc progress / current state. Great idea!

**Comment by vdice** [comment]
Also, worth repeating, structure and/or individual doc sections not set in stone.  As we fill out documentation, there's bound to be re-org, trimming, additions, etc.

**Comment by vdice** [comment]
Neat!  Any item in the task list can be converted to an issue with one click:

<img width="938" alt="Screen Shot 2021-07-20 at 10 47 50 AM" src="https://user-images.githubusercontent.com/9322017/126363716-bc40caac-e802-425b-8748-819926bc072a.png">
