### ISSUE TITLE
v2.0.0 Release Checklist

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade#1702]
As we close in on v2 going GA, here is a checklist of things that have to happen-- and a rough order in which they must happen:

- RC:
    - [x] Release v2.0.0-beta.4.
    - [x] Establish and blog about maintenance window / sunset plans for v1.x.
    - [x] Resolve all issues/PRs that are labeled as RC blockers.
    - [x] Update Brigade SDK for JS/TS to use stable API version (`brigade.sh/v2`).
    - [x] Release Brigade SDK for JS/TS v2.0.0-rc.1.
    - [x] Update Brigadier polyfill to use updated Brigade SDK for JS/TS v2.0.0-rc.1.
    - [x] Update API server to serve stable API version (`brigade.sh/v2`).
    - [x] Update SDK for Go to use stable API version (`brigade.sh/v2`).
    - [x] Update examples to use stable API version (`brigade.sh/v2`).
    - [x] Release v2.0.0-rc.1.
    - [x] Update examples to use Brigadier v2.0.0-rc.1.
    - [x] Update all gateways and peripherals to use Go SDK v2.0.0-rc.1 and stable API version (`brigade.sh/v2`).
    - [x] Blog about the release candidate.
    - [x] Tweet about the release candidate

- Repo maintenance:
    - [ ] ~~`master` branch needs to be renamed to `v1`~~
    - [ ] ~~`v2` branch needs to be renamed to `main`~~
    - [x] `v1` branch needs to be forked from `master`
    - [x] `master` needs to be renamed to `main`
    - [x] `v2` branch needs to be merged into `main`
        This would be a giant PR that no one would possibly ever review. The best approach to this activity is probably for two maintainers to pair to accomplish this-- one to drive and one to observe / sign off.
    - [ ] Other TBD steps may be required to ensure anyone consuming Go packages from v1.x isn't broken. This will require some research and experimentation.
    - [x] Update examples to use new location of JSON schemas. (Ideally, we should put a copy of the schema someplace nicer.)

- Doc and web site:
    - [x] v2 docs need to become the _main_ docs site.
    - [ ] Web site still requires brand refresh.

- GA:
    - [x] Test and release a v1.4.2 or v1.5.0, as well as updated charts. This _must_ happen prior to the v2.0.0 release so that when 2.0.0 _is_ released it will be the newest, most prominent thing on the releases page.
    - [x] Release Brigade SDK for JS/TS v2.0.0
    - [x] Update Brigadier polyfill to use updated Brigade SDK for JS/TS v2.0.0.
    - [x] Release v2.0.0.
    - [x] Update examples to use Brigadier v2.0.0.
    - [x] Update all gateways and peripherals to use Go SDK v2.0.0.
    - [x] Blog about the release.
    - [x] Tweet about the release.

@vdice and @karenhchu , please feel free to add to this list.
