### ISSUE TITLE
META: Update licenses across brigadecore repos

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#852]
For Brigade repos migrated from the Azure org (or other contributor orgs), licenses may still need to be updated to de-reference Microsoft (or other).

As an updated example, see https://github.com/brigadecore/charts/blob/master/LICENSE 

Repos include:
 - [x] https://github.com/brigadecore/brigade (this one)
 - [x] https://github.com/brigadecore/brigade-github-app
 - [x] https://github.com/brigadecore/kashti
 - [x] https://github.com/brigadecore/brigadier
 
Other?

cc @radu-matei @technosophos

**Comment by vdice** [comment]
PRs have been submitted to all of the repos listed above in the description...
