### ISSUE TITLE
META: Add DCO to brigadecore repos

### ISSUE THREAD

**Issue by vdice** [brigadecore/brigade#853]
For Brigade repos migrated from the Azure org (or other contributor orgs), we may still want/need to add instructions on how contributors can accept Developer's Certificate of Origin and sign their commits accordingly.

Repos include:
 - [x] https://github.com/brigadecore/brigade (this one)
 - [x] https://github.com/brigadecore/brigade-github-app
 - [x] https://github.com/brigadecore/kashti
 - [x] https://github.com/brigadecore/brigadier
 
Other?

Once updated, we can then add the [dco bot](https://github.com/apps/dco) for an automated PR check.

 - [x] add the [dco bot](https://github.com/apps/dco)

cc @radu-matei @technosophos

**Comment by vdice** [comment]
All PRs issued; closing.
